name: example
description: sumtypes package example
version: 0.0.1
homepage: https://github.com/mateusfccp/sumtypes
repository: https://github.com/mateusfccp/sumtypes

environment:
  sdk: ">=2.7.0 <3.0.0"
  quiver:

dependencies:
    sumtypes_annotation:
      path: ../sumtypes_annotation

dev_dependencies:
  sumtypes:
    path: ../sumtypes
  build_runner: ^1.8.0
