name: example
description: Algebraic Data Types
version: 0.0.1
homepage: https://github.com/mateusfccp/magiceye
repository: https://github.com/mateusfccp/magiceye

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  adt:
    path: ../
  build_runner: ^1.8.0