name: example
description: sumtypes package example
version: 0.0.1
homepage: https://github.com/mateusfccp/sumtypes
repository: https://github.com/mateusfccp/sumtypes

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  sumtypes:
    path: ../
  build_runner: ^1.8.0
