builders:
  sumtypes_generator:
    import: "package:sumtypes/builder.dart"
    builder_factories: ["sumtypeBuilder"]
    build_extensions: {".dart": ["sumtypes.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

