builders:
  adt_generator:
    import: "package:adt/builder.dart"
    builder_factories: ["algebraicBuilder"]
    build_extensions: {".dart": ["adt.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

