name: sumtypes
description: Dart safe, generated sum types
version: 0.0.1
homepage: https://github.com/mateusfccp/sumtypes
repository: https://github.com/mateusfccp/sumtypes

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.2.2
  source_gen: ^0.9.5

dev_dependencies:
  pedantic: ^1.8.0